### ISSUE TITLE
Rethink zipbackup?

### ISSUE THREAD

**Issue by pabo3000** [collective/collective.recipe.backup#24]
If I got it right zipbackup is mainly for development purpose. Wouldn't it be much nicer to have only one zip archive as a backup? It should contain everything from var/zipbackups and the var/blobstoragezip. it should be located in the buildout-dir. Then it would be rather convenient to scp only one file to your dev env. Of course bin/ziprestore should replace both filestorage and blobstorage.

**Comment by mauritsvanrees** [comment]
zipbackup is meant to make it easier to copy all data from one computer (usually production) to another (development laptop or also a testing server).

The code is easier when the repozo and rsync parts remains separated.

Biggest downside to me would be that you need more space. You need the Data.fs three times while doing this: the original, the standalone backup, and the tarball that is being created. When you are done, the standalone backup can be removed (automatically) but then you have already run out of disk space...
