### ISSUE TITLE
Disable fullbackup script by default

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/collective.recipe.backup#28]
I am inclined to no longer create the `fullbackup` script by default. I don't remember the last time I used it. When you pack the database and run the normal `backup` script, you get a full backup anyway.

**Comment by fiterbek** [comment]
This is also the case for us. 

The pack & backup combination is more efficient, and in the exceptional case a separate full backup is needed, we tend to use the snapshotbackup / zipbackup features.
