### ISSUE TITLE
Backup version files etc.

### ISSUE THREAD

**Issue by espenmn** [collective/collective.recipe.backup#38]
bin/backup takes care of backing up you data, but could it be an idea to also make it possible to have it make/backup a base.cfg, versions.cfg etc, making it possible to 'restore to another place from one place).

.... I know that all versions should be pinned, but sometimes they are not and one needs to 'dig around'...

**Comment by mauritsvanrees** [comment]
So with an extra option `backup-buildout = true`, `bin/backup` would backup the filestorage, blobstorage and the buildout configs? Your reason would be that, for example, it may not make sense to restore data from Plone 4.3 when your current buildout config is for 5.0? I can see some use for this, but I am not enthousiastic.

- What would it copy? Just buildout.cfg? Anything that buildout.cfg extends, including remote configs (which makes sense)? buildout.cfg may point to templates, with `collective.recipe.template`. Do we somehow find and copy those? Where does it end?

- What would `bin/restore` do then? Copy over the data and the buildout configs and run `bin/buildout`? I guess that is something that new Plone users would expect, and that experienced Plone users would run away from, screaming.

- I put my customer buildouts in version control, with tags, and have a `HISTORY.txt` and `version.txt` in it. If we really need old data and an old version of the buildout configs, I would check in `HISTORY.txt` which tag of the buildout would fit which backup. Wouldn't that be enough?

**Comment by gforcada** [comment]
I'm also on @mauritsvanrees side in this case, the amount of problems to get this backup right are far too great and the *proper* solution is to use deployment best practices to keep  things well groomed and organized.

There are more problems as well: what about packages in a possible virtualenv?
