### ISSUE TITLE
Info about getting repozo-script for standalones

### ISSUE THREAD

**Issue by ksuess** [collective/collective.recipe.backup#42]
As mentioned by @tmassman the dependent-scripts parameter is necessary to get a repozo-script.
It would be helpful to add this to the readme.txt

**Comment by mauritsvanrees** [comment]
Good point. I guess it might have worked before with earlier ZODB3 versions, but not anymore. Anyway, fixed in a83db8b7b4b29883cb151176f013731806cdb324.
