### ISSUE TITLE
[feature] (soft) symlink to newest blobstorage in blob_timestamps mode

### ISSUE THREAD

**Issue by fredvd** [collective/collective.recipe.backup#48]
One handy side effect of the initial 'rotating' blobstorage setup was that blobstorage.0 in the backup directory always points to the most recent blob part of the backup.  

With the new blob_timestamps mode, bin/restore searches for the 'nearest' blobstorage backup linked to the available Data.fs timepoints, but in some setups I have automated restore of the latest content data from production to test by remote mounting or rsyncing the production blob backup directories and not using bin/restore or bin/altrestore.

Could the backup script create a soft symlink 'latest' in the blobs directory that is automatically updated at the end of a backup run to point to the latest backupped blobstorage.20XX-XX-XX timestamped directory? That way there's a stable directory to the latest blobstorage. 

Symlinks: 
in case of rsync I'd might run into issues with rsync not following symlinks, but that can be fixed by passing -L.  Creating a hardlink is probably not wise because that would re-introduce a daily changing blobstorage directory, what blob_timestamps mode tries to avoid in case the backup-directory itself is mirrorred off site)

**Comment by mauritsvanrees** [comment]
I have release 4.1.0 with this.
