### ISSUE TITLE
Drop support for additional filestorages

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/collective.recipe.backup#64]
I have myself used `Data.fs` and `Catalog.fs`, but that was long ago. If someone still really needs this, the alternative is probably to create one backup script for each filestorage.

**Comment by gforcada** [comment]
🤚🏾 we are still using this 😅

**Comment by mauritsvanrees** [comment]
Please don't. ;-)
Well, I will see how much effort it is to keep the code working. Good that you speak up.

**Comment by gforcada** [comment]
I would love to move away, I need to have time and some guidance on how to merge a catalog back, I haven't seen much references 😕

**Comment by davisagli** [comment]
@gforcada It has been a long time since I used that configuration, and I don't think I ever went back in the direction of merging them together again. But I would try one of these approaches:
1. zexp export portal_catalog, restart zope without the mountpoint, and zexp import into the correct location
2. restart zope without the mountpoint, recreate portal_catalog, and do a full reindex

**Comment by mauritsvanrees** [comment]
One of those might be best, although for the second one you need to take care the you have all indexes and metadata columns. Maybe make a GenericSetup export of the catalog first, so you can reimport its settings later.

What I just tried in a standard Plone 6 site, with everything in one filestorage:
- In the ZMI of site A copy the portal_catalog and paste it in a new Plone Site B.
- Remove the catalog in site A.
- Copy and paste the catalog from B to A.

I am not sure if this also works in a separate fs: maybe you are then just copying the MountPoint object, which would not help.

Ah, but I recently had a client where two filestorages were used. Only they did not use mount points, but they had code to open the second database and read it. This caused several problems, so I rewrote it to move the data back into the main database.  Code is something like this:

```
from ZODB.FileStorage import FileStorage
from contextlib import contextmanager
from ZODB.DB import DB

@contextmanager
def client_store():
    storage = FileStorage("var/filestorage/client.fs", read_only=True)
    db = DB(storage)
    connection = db.open()
    try:
        yield connection.root()
    finally:
        connection.close()
        db.close()

with client_store() as old_store:
    if old_store is not None:
        old_licences = old_store.get("licence", {})
        log.info('Found %d licences in old client store.', len(old_licences))
        if len(old_licences) > 0:
            for key, value in old_licences.items():
                # We cannot copy an object from one database to another.
                # It would lead to a ConnectionStateError.
                # We need to create a new object instead.
                licences[key] = ClientProduct.from_product(value)
            log.info("Copied old licences to new annotation.")
            return licences
```

In their case, the root of the storage had two items:

```
root.setdefault('order', OOBTree())
root.setdefault('licence', {})
```

I suppose in your case `root["portal_catalog"]` exists.
Ah, but copying it will likely lead to ConnectionStateErrors, like the comment in the code says. You could import the `ZCatalog` class and create a new catalog object with this. But the same errors would likely happen for all the indexes, for the `_catalog` object, etcetera.
So best forget I said anything. ;-)

One of the options from David is probably best. Afterwards, a catalog clear and rebuild would be good. Or try https://github.com/collective/collective.catalogcleanup

**Comment by gforcada** [comment]
Oops, 😊 I did not say anything! 🙇🏾 thanks a lot for the ideas and examples 👍🏾 

I thinks that David's 2nd option is our way to go, as we are already having some problems with the objects that are stored there, causing weird tracebacks. Fortunately, it was not a blocker for the python 3 migration we did a few months ago.

For the issue at hand though, you can safely ignore my first comment and delete the code, we will bring the catalog back on the `Data.fs` one way or another, and probably at the same time even move to `relstorage`, as `zc.zrs` is not running on newer versions of ZODB, and seems that there is not that many eyeballs looking into it 😓

**Comment by mauritsvanrees** [comment]
Done.
